title: Wagner Abreu
description: Analista e Desenvolvedor de Sistemas. Pós Graduando em Engenharia e Qualidade de Software - Unipê
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
